### ISSUE TITLE
Can't seem to run train.py on OS X catalina

### ISSUE THREAD

**Issue by KAltieri** [amidos2006/gym-pcgrl#8]
Hello,

I tried to run the train.py file when playing around with the project, and can't seem to run it.  When I try to run it through terminal with everything installed i get the error: 
File "train.py", line 81
    **kwargs,
     ^
SyntaxError: invalid syntax

I double checked and all my pythons, pips, tensorflow and stable-baseline are up to date.

So I tried it through docker.  However, when I try to run it through docker I get this: docker: Error response from daemon: Unknown runtime specified nvidia.

I've tried searching for other ways to run it and I can't seem to find anything.  Any help would be appreciated.

**Comment by amidos2006** [comment]
What is your python version?

**Comment by KAltieri** [comment]
Python version is: Python 2.7.16
Python3 version is: Python 3.8.1

**Comment by amidos2006** [comment]
First of all, make sure you are always using new python (3.5 or newer) don't try 2.7 ever and make sure that when you try to run train.py that this is the case.

The error you are getting is because you are trying to run the code using python 2.7. Here is an experiment showing that **varName is not supported in 2.7 (copied from my console):
![Error with Python 2.7](https://i.imgur.com/ImmY8cx.png)

Here is the same experiment with newer python (3.5.2):
![Running Successful](https://i.imgur.com/iXthc6o.png)

To make sure this is not happening always use anaconda to manage your virtual environment so there is not two python version installed at the same place.

**Comment by KAltieri** [comment]
Okay so I tried the anaconda way of doing it based on the ReadMe and got this error when trying to run the train.py after installing the necessary dependencies:

Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from model import FullyConvPolicyBigMap, FullyConvPolicySmallMap, CustomPolicyBigMap, CustomPolicySmallMap
ImportError: cannot import name 'FullyConvPolicyBigMap' from 'model' (/Users/Kevin/Desktop/gym-pcgrl/model.py)

Is there a step that I misread from the readme?  Thanks!

**Comment by amidos2006** [comment]
Are you sure the model.py is there beside train.py because that error means it can't see model.py

**Comment by KAltieri** [comment]
the model.py is there, I have made no changes to the original repo

**Comment by amidos2006** [comment]
mmm... I don't get why it can't see that python file. Just try in the python console to import any class from model.py if It can't maybe OSX Catalina has some security issues.

**Comment by KAltieri** [comment]
alright thanks

**Comment by smearle** [comment]
There are a few different "Policy" classes defined in model.py, maybe train.py is trying to import a Policy that is not defined in model.py. You might get away with commenting out the offending import.

**Comment by KAltieri** [comment]
So that tip was helpful, I got rid of the FullyConvPolicyBigMap issue, but now my new issue is that its looking for a file called policy.  Is there one that should be there that I'm missing, or is it something else entirely?

 Traceback (most recent call last):
  File "train.py", line 8, in <module>
    from policy import PPO2
ModuleNotFoundError: No module named 'policy'

**Comment by smearle** [comment]
You must be on the experimental FractalNet branch.
Try
`git checkout master`
then open train.py: there should be no such import line (instead, on line 8, we'll be importing policies from stable_baselines').

**Comment by amidos2006** [comment]
Yup, I was trying to understand what is happening because that code looks old with some new one.

**Comment by KAltieri** [comment]
Okay thanks! Maybe thats where all my issues are stemming from

**Comment by smearle** [comment]
I just tried cloning a fresh repository, and can confirm that was on the master branch, and code was able to run (after making a 'runs' directory to log training progress). You must have accidentally switched branches somehow.
You can run `git branch -a` to view all available branches (I should probably delete most of them...), and check which branch you are on.
